version: "3.8"
services:
    app:
        build: .
        container_name: app-node
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - database
            - redis
        env_file:
            - .env
        volumes:
            - ./data/logs:/app/data/logs

    database:
        container_name: app-database
        image: mongo:7.0
        restart: always
        volumes:
            - ./db-data:/data/db
        ports:
            - "27018:27017"

    redis:
        container_name: app-redis
        image: redis:7-alpine
        restart: always
        ports:
            - "6379:6379"
